version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: yuzu-postgres
    environment:
      POSTGRES_USER: yuzu
      POSTGRES_PASSWORD: yuzu_dev_password  # Use a secure password in production
      POSTGRES_DB: yuzu
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yuzu"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - yuzu-network

  minio:
    image: minio/minio
    container_name: yuzu-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin  # Use a secure password in production
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - yuzu-network

  yuzu-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yuzu-web
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DataStorageConfig__ConnectionString=Host=postgres;Database=yuzu;Username=yuzu;Password=yuzu_dev_password
      - S3Settings__ServiceUrl=http://minio:9000
      - S3Settings__BucketName=static
      - S3Settings__BackgroundsContainer=backgrounds
      - S3Settings__AccessKey=minioadmin
      - S3Settings__SecretKey=minioadmin
      - MailConnectionConfig__smtpServer=mailhog
      - MailConnectionConfig__smtpUsername=yuzu
      - MailConnectionConfig__smtpPassword=Apollo13!
      - MailConnectionConfig__smtpPort=1025
    ports:
      - "8080:80"
    networks:
      - yuzu-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - yuzu-network

networks:
  yuzu-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data: