name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: custom-runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          echo "Installing Docker and dependencies..."
          apk add --no-cache docker docker-cli-buildx

          # Start dockerd directly (without using service or rc-update)
          echo "Starting Docker daemon..."
          dockerd &

          # Wait for Docker to start
          echo "Waiting for Docker to start..."
          sleep 10

          # Verify Docker is running
          docker info || (echo "Docker failed to start properly" && exit 1)

      - name: Get version tag
        id: get_version
        run: |
          if [[ ${{ github.ref_type }} == 'tag' && ${{ github.ref_name }} == v* ]]; then
            # If this is a tag push like v1.2.3, use that as version without the 'v'
            VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            # Otherwise use commit SHA for untagged builds
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
            echo "version=$SHORT_SHA" >> $GITHUB_OUTPUT
          fi
        
      - name: Login to Scaleway Container Registry
        run: |
          mkdir -p ~/.docker
          echo '{"auths":{"rg.fr-par.scw.cloud":{"auth":"'$(echo -n "nologin:${{ secrets.SCW_SECRET_KEY }}" | base64)'"}}}' > ~/.docker/config.json
          chmod 600 ~/.docker/config.json
          # Verify the login worked
          cat ~/.docker/config.json
          echo "Docker login configured via config.json"

      - name: Build Docker image
        run: docker build -t yuzu:latest .

      - name: Tag Docker images
        run: |
          docker tag yuzu:latest rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:latest
          docker tag yuzu:latest rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:${{ steps.get_version.outputs.version }}

      - name: Push Docker images to registry
        run: |
          docker push rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:latest
          docker push rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:${{ steps.get_version.outputs.version }}