name: Build and Push Docker Image (Manual Only)

# NOTE: This workflow is for manual builds only.
# For automated builds and deployment, use the build-push-deploy.yml workflow instead.

on:
  # Only manual trigger is enabled
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: custom-runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version tag and build number
        id: get_version
        run: |
          # Make generate-build-number.sh executable
          chmod +x build/generate-build-number.sh

          # Use git commit count for build number
          BUILD_NUMBER=$(./build/generate-build-number.sh)
          echo "Build number from git commits: $BUILD_NUMBER"

          # Store the build number for later steps
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

          # Get version tag as before
          if [[ ${{ github.ref_type }} == 'tag' && ${{ github.ref_name }} == v* ]]; then
            # If this is a tag push like v1.2.3, use that as version without the 'v'
            VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            # Otherwise use commit SHA for the version tag
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
            echo "version=$SHORT_SHA" >> $GITHUB_OUTPUT
          fi
        
      - name: Configure Docker Credentials
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        run: |
          # Login to Scaleway registry
          echo "$SCW_SECRET_KEY" | docker login rg.fr-par.scw.cloud -u nologin --password-stdin
          echo "Docker login completed"

      - name: Build Docker image with version information
        run: |
          # Pass build number and git commit to Docker build
          docker build \
            --build-arg BUILD_NUMBER=${{ steps.get_version.outputs.build_number }} \
            --build-arg GIT_COMMIT=${{ github.sha }} \
            -t yuzu:latest .

      - name: Tag Docker images
        run: |
          docker tag yuzu:latest rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:latest
          docker tag yuzu:latest rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:${{ steps.get_version.outputs.version }}

      - name: Push Docker images to registry
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        run: |
          echo "Pushing image with tag: latest"
          docker push rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:latest
          
          echo "Pushing image with tag: ${{ steps.get_version.outputs.version }}"
          docker push rg.fr-par.scw.cloud/cr-yuzu-par-1/yuzu-web:${{ steps.get_version.outputs.version }}