name: Test Repository Access (Correct Path)

# This workflow is only for testing repository access with the correct path
# It doesn't build or push Docker images

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      ssh_key_type:
        description: 'SSH key type to use (rsa, ed25519)'
        required: true
        default: 'rsa'

jobs:
  test-repo-access:
    runs-on: custom-runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH tools
        run: |
          echo "Installing SSH tools..."
          apk add --no-cache openssh-client
          echo "SSH tools installed successfully"

      - name: Setup SSH key (RSA)
        if: ${{ github.event.inputs.ssh_key_type == 'rsa' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Generate public key from private key
          echo "Generating RSA public key from private key..."
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          
          # Display key fingerprint
          echo "RSA key fingerprint:"
          ssh-keygen -l -f ~/.ssh/id_rsa.pub
          
          echo "===== RSA PUBLIC KEY CONTENT ====="
          cat ~/.ssh/id_rsa.pub
          echo "=================================="

      - name: Setup SSH key (ED25519)
        if: ${{ github.event.inputs.ssh_key_type == 'ed25519' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Generate public key from private key
          echo "Generating ED25519 public key from private key..."
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
          chmod 644 ~/.ssh/id_ed25519.pub
          
          # Display key fingerprint
          echo "ED25519 key fingerprint:"
          ssh-keygen -l -f ~/.ssh/id_ed25519.pub
          
          echo "===== ED25519 PUBLIC KEY CONTENT ====="
          cat ~/.ssh/id_ed25519.pub
          echo "======================================"

      - name: Add server to known hosts
        run: |
          # Add gitea server to known hosts (with custom port 29418)
          ssh-keyscan -p 29418 gitea.watermelonsoft.eu >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          
          if [[ "${{ github.event.inputs.ssh_key_type }}" == "rsa" ]]; then
            # Use RSA key
            timeout 10 ssh -vvv -i ~/.ssh/id_rsa -p 29418 git@gitea.watermelonsoft.eu || true
          else
            # Use ED25519 key
            timeout 10 ssh -vvv -i ~/.ssh/id_ed25519 -p 29418 git@gitea.watermelonsoft.eu || true
          fi
          
          echo "SSH test completed"

      - name: Configure Git
        run: |
          git config --global user.name "Gitea Workflow"
          git config --global user.email "noreply@gitea.local"

      - name: Test clone repository with correct path
        run: |
          echo "Attempting to clone repository via SSH..."
          
          if [[ "${{ github.event.inputs.ssh_key_type }}" == "rsa" ]]; then
            # Clone with RSA key
            export GIT_SSH_COMMAND="ssh -vv -i ~/.ssh/id_rsa -p 29418 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
            echo "Cloning repository with path: Yuzu/YuzuDeploy"
            git clone ssh://git@gitea.watermelonsoft.eu:29418/Yuzu/YuzuDeploy.git test-clone
          else
            # Clone with ED25519 key
            export GIT_SSH_COMMAND="ssh -vv -i ~/.ssh/id_ed25519 -p 29418 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
            echo "Cloning repository with path: Yuzu/YuzuDeploy"
            git clone ssh://git@gitea.watermelonsoft.eu:29418/Yuzu/YuzuDeploy.git test-clone
          fi
          
          # Check repository contents
          cd test-clone
          echo "Successfully cloned repository. Contents:"
          ls -la
          
          echo "Clone test successful!"