apiVersion: v1
kind: Config
clusters:
- name: local-cluster
  cluster:
    server: https://localhost:6443
    insecure-skip-tls-verify: true
contexts:
- name: local-context
  context:
    cluster: local-cluster
    user: local-user
current-context: local-context
users:
- name: local-user
  user:
    # If your cluster requires authentication, you'll need to add credentials here
    # For now, we're using insecure-skip-tls-verify: true