# IngressRoute for Yuzu application with existing wildcard certificate
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: yuzu-route
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`yuzu.yourdomain.com`)
    kind: Rule
    services:
    - name: yuzu-web-service
      port: 80
    middlewares:
    - name: yuzu-compress
    - name: yuzu-headers
  tls:
    secretName: wildcard-yourdomain-tls
---
# Define middlewares for compression and security headers
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: yuzu-compress
spec:
  compress: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: yuzu-headers
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: "SAMEORIGIN"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
# TLS options configuration for enhanced security
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: modern-tls
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305